name: image-anonymisation
channels:
  - conda-forge
  - defaults
dependencies:
  - cython=0.29.15
  - h5py=2.10.0
  - mkl=2019.4
  - numpy=1.17.0
  - pip=20.0.2
  - pytest=5.4.1
  - python=3.7.6
  - pyyaml=5.3.1
  - scipy=1.3.1
  - sphinx=2.4.4
  - tensorflow-gpu=2.1.0
  - tqdm=4.43.0
  - xmltodict=0.12.0
  - pip:
    - cx-oracle==7.3.0
    - func-timeout==4.3.5
    - iso8601==0.1.12
    - m2r==0.2.1
    - opencv-python==4.2.0.32
    - pillow==7.0.0
    - webp==0.1.0a15